from c4dev.commands.basecommand     import BaseCommand
from c4dev.commands.updatecommand   import UpdateCommand
from c4dev.commands.compilecommand  import CompileCommand
from c4dev.commands.validatecommand import ValidateCommand
from c4dev.commands.installcommand  import InstallCommand
from c4dev.commands.licensecommand  import LicenseCommand
from c4dev.commands.licensescommand  import LicensesCommand
from c4dev.commands.unsquishcommand  import UnsquishCommand
from c4dev.commands.infocommand  import InfoCommand